pipeline:
  identifier: Build_Cager2808_React_App_Harness_1703926850297
  name: Build React-App-Harness
  orgIdentifier: default
  projectIdentifier: ReactAppHarness
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698735122136
        repoName: Cager2808/React-App-Harness
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - stepGroup:
                  name: Upload and Build
                  identifier: Upload_and_Build
                  steps:
                    - parallel:
                        - step:
                            type: S3Upload
                            name: Artifacts_S3
                            identifier: Artifacts_S3
                            spec:
                              connectorRef: awsreactharness
                              region: ap-south-1
                              bucket: react-app-artifacts-demo
                              sourcePath: Artifacts/
                        - step:
                            type: BuildAndPushDockerRegistry
                            name: BuildAndPushDockerRegistry
                            identifier: BuildAndPushDockerRegistry
                            spec:
                              connectorRef: account.harnessImage
                              repo: singha07/react-app-harness/
                              tags: <+input>
              - step:
                  type: Run
                  name: npm_build
                  identifier: npm_build
                  spec:
                    shell: Sh
                    command: npm build
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: true
            paths: []
        type: CI
        description: ""
